#!/bin/bash
# Clawdbot Sentinel Installer
# Installs and configures the Sentinel health monitoring system

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTINEL_DIR="$HOME/.clawdbot/sentinel"
CONFIG_FILE="$HOME/.clawdbot/sentinel.conf"
LOG_DIR="$SENTINEL_DIR/logs"
LAUNCHD_PLIST="$HOME/Library/LaunchAgents/com.clawdbot.sentinel.plist"

# Default settings
DEFAULT_CHECK_INTERVAL=300
DEFAULT_MAX_BUDGET=2.00
DEFAULT_MAX_TURNS=20

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                   Clawdbot Sentinel Installer                 ║"
echo "║         Automated health monitoring with Claude Code          ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# =============================================================================
# CHECKS
# =============================================================================

echo -e "${BLUE}Checking requirements...${NC}"

# Check for macOS
if [ "$(uname)" != "Darwin" ]; then
    echo -e "${RED}Error: Sentinel currently only supports macOS${NC}"
    echo "Linux support (systemd) coming soon."
    exit 1
fi

# Check for clawdbot
if ! command -v clawdbot &> /dev/null; then
    echo -e "${RED}Error: clawdbot not found${NC}"
    echo "Please install Clawdbot first: https://docs.clawd.bot/"
    exit 1
fi
echo -e "${GREEN}✓${NC} Clawdbot found: $(which clawdbot)"

# Check for claude
if ! command -v claude &> /dev/null; then
    echo -e "${RED}Error: claude (Claude Code) not found${NC}"
    echo "Please install Claude Code first: https://claude.ai/claude-code"
    exit 1
fi
echo -e "${GREEN}✓${NC} Claude Code found: $(which claude)"

# Check for existing installation
if [ -f "$LAUNCHD_PLIST" ]; then
    echo -e "${YELLOW}Warning: Sentinel is already installed${NC}"
    read -p "Do you want to reinstall? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
    # Unload existing service
    launchctl unload "$LAUNCHD_PLIST" 2>/dev/null || true
fi

# =============================================================================
# CONFIGURATION
# =============================================================================

echo ""
echo -e "${BLUE}Configuration${NC}"
echo "Press Enter to accept defaults shown in brackets."
echo ""

# Check interval
read -p "Health check interval in seconds [$DEFAULT_CHECK_INTERVAL]: " CHECK_INTERVAL
CHECK_INTERVAL=${CHECK_INTERVAL:-$DEFAULT_CHECK_INTERVAL}

# Max budget
read -p "Maximum USD per repair attempt [$DEFAULT_MAX_BUDGET]: " MAX_BUDGET
MAX_BUDGET=${MAX_BUDGET:-$DEFAULT_MAX_BUDGET}

# Max turns
read -p "Maximum Claude Code turns per repair [$DEFAULT_MAX_TURNS]: " MAX_TURNS
MAX_TURNS=${MAX_TURNS:-$DEFAULT_MAX_TURNS}

# =============================================================================
# INSTALLATION
# =============================================================================

echo ""
echo -e "${BLUE}Installing Sentinel...${NC}"

# Create directories
mkdir -p "$SENTINEL_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$HOME/Library/LaunchAgents"
echo -e "${GREEN}✓${NC} Created directories"

# Copy health check script
cp "$SCRIPT_DIR/scripts/health-check.sh" "$SENTINEL_DIR/health-check.sh"
chmod +x "$SENTINEL_DIR/health-check.sh"
echo -e "${GREEN}✓${NC} Installed health check script"

# Copy CLAUDE.md context file
cp "$SCRIPT_DIR/config/CLAUDE.md" "$HOME/.clawdbot/CLAUDE.md"
echo -e "${GREEN}✓${NC} Installed CLAUDE.md context file"

# Create configuration file
cat > "$CONFIG_FILE" << EOF
# Clawdbot Sentinel Configuration
# Generated by installer on $(date)

# Health check interval in seconds
CHECK_INTERVAL=$CHECK_INTERVAL

# Maximum USD to spend per repair attempt
MAX_BUDGET_USD=$MAX_BUDGET

# Maximum Claude Code turns per repair
MAX_TURNS=$MAX_TURNS

# Gateway URL to monitor
GATEWAY_URL="http://127.0.0.1:18789"

# Tools Claude Code can use for repairs
ALLOWED_TOOLS="Bash,Read,Edit,Glob,Grep,WebFetch"

# Seconds to wait before confirming gateway is down
CONFIRMATION_DELAY=5

# Maximum age of lock file before considering it stale (seconds)
MAX_LOCK_AGE=1800

# Keep logs for this many days (0 = keep forever)
LOG_RETENTION_DAYS=30
EOF
echo -e "${GREEN}✓${NC} Created configuration file"

# Generate launchd plist from template
sed -e "s|{{SENTINEL_DIR}}|$SENTINEL_DIR|g" \
    -e "s|{{LOG_DIR}}|$LOG_DIR|g" \
    -e "s|{{HOME}}|$HOME|g" \
    -e "s|{{CHECK_INTERVAL}}|$CHECK_INTERVAL|g" \
    -e "s|{{CONFIG_FILE}}|$CONFIG_FILE|g" \
    "$SCRIPT_DIR/launchd/com.clawdbot.sentinel.plist.template" > "$LAUNCHD_PLIST"
echo -e "${GREEN}✓${NC} Created launchd service"

# Load the service
launchctl load "$LAUNCHD_PLIST"
echo -e "${GREEN}✓${NC} Started Sentinel service"

# =============================================================================
# SHELL ALIASES (optional)
# =============================================================================

echo ""
read -p "Add 'sentinel' command aliases to your shell? (Y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    # Detect shell
    SHELL_RC=""
    if [ -n "${ZSH_VERSION:-}" ] || [ -f "$HOME/.zshrc" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -n "${BASH_VERSION:-}" ] || [ -f "$HOME/.bashrc" ]; then
        SHELL_RC="$HOME/.bashrc"
    fi

    if [ -n "$SHELL_RC" ]; then
        # Check if already added
        if ! grep -q "# Clawdbot Sentinel aliases" "$SHELL_RC" 2>/dev/null; then
            cat >> "$SHELL_RC" << 'EOF'

# Clawdbot Sentinel aliases
sentinel() {
    case "$1" in
        status)
            launchctl list | grep sentinel && echo "" && tail -5 ~/.clawdbot/sentinel/logs/health.log
            ;;
        check)
            ~/.clawdbot/sentinel/health-check.sh
            ;;
        logs)
            tail -f ~/.clawdbot/sentinel/logs/health.log
            ;;
        repairs)
            tail -f ~/.clawdbot/sentinel/logs/repairs.log
            ;;
        *)
            echo "Usage: sentinel {status|check|logs|repairs}"
            ;;
    esac
}
EOF
            echo -e "${GREEN}✓${NC} Added aliases to $SHELL_RC"
            echo "  Run 'source $SHELL_RC' or start a new terminal to use them."
        else
            echo -e "${YELLOW}!${NC} Aliases already exist in $SHELL_RC"
        fi
    else
        echo -e "${YELLOW}!${NC} Could not detect shell config file"
    fi
fi

# =============================================================================
# COMPLETE
# =============================================================================

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Sentinel installed successfully!                 ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Configuration:  $CONFIG_FILE"
echo "Logs:           $LOG_DIR/"
echo "Check interval: Every $CHECK_INTERVAL seconds"
echo ""
echo "Commands:"
echo "  sentinel status   - Check service status"
echo "  sentinel check    - Manually trigger health check"
echo "  sentinel logs     - View health logs"
echo "  sentinel repairs  - View repair logs"
echo ""
echo "To modify settings, edit: $CONFIG_FILE"
echo "Then restart: launchctl unload $LAUNCHD_PLIST && launchctl load $LAUNCHD_PLIST"
echo ""
